all: exercise01 exercise02 exercise03 exercise04 exercise05 exercise06 exercise07



exercise01: exercise01.o
	g++ exercise01.o -o exercise01.exe

exercise01.o: exercise01.cpp
	g++ -std=c++11 -c exercise01.cpp



exercise02: exercise02.o
	g++ exercise02.o -o exercise02.exe

exercise02.o: exercise02.cpp
	g++ -std=c++11 -c exercise02.cpp



exercise03: exercise03.o
	g++ exercise03.o -o exercise03.exe

exercise03.o: exercise03.cpp
	g++ -c exercise03.cpp



exercise04: exercise04.o
	g++ exercise04.o -o exercise04.exe

exercise04.o: exercise04.cpp
	g++ -c exercise04.cpp



exercise05: exercise05.o
	g++ exercise05.o -o exercise05.exe

exercise05.o: exercise05.cpp
	g++ -c exercise05.cpp



exercise06: exercise06.o
	g++ exercise06.o -o exercise06.exe

exercise06.o: exercise06.cpp
	g++ -c exercise06.cpp



exercise07: exercise07.o
	g++ exercise07.o -o exercise07.exe

exercise07.o: exercise07.cpp
	g++ -c exercise07.cpp



clean:
	rm -rf exercise*.o exercise*.exe *.o